# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368b92c8c093fed5e51e5734644fdc4b48b7391e7c566ca74faef586d1c41396a41af78449dd44f37240ca2c349218f98afdcc63997cf6cf8070fd047bbc9f1e

test:
  secret_key_base: cda5e40398c14bc33bb309e58c7049f5309f54e0710042b49131a86d35b549c486700a61144791deb5764047b0d98f697769bf3dc749dbbb1689ba7498b4881b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
